---
.travis.yml:
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_ub
      - ---travis_el
      - travis_el6
      - travis_el7
      # - travis_el8 # Uncomment after adding el8 support and run pdk update
