sudo: false
language: ruby
bundler_args: --without release beaker
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
env:
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4.9"
matrix:
  include:
    - rvm: '2.2'
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-docker"
      script: travis_retry bundle exec rake beaker
      bundler_args: --without release
  exclude:
    - rvm: '2.2'
      env: PUPPET_GEM_VERSION="~> 3.7"
    - rvm: '2.0'
      env: PUPPET_GEM_VERSION="~> 4.9"
  fast_finish: true
notifications:
  email: false
