name    'jhoblitt-udev'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-udev'
source 'https://github.com/jhoblitt/puppet-udev.git'
summary 'Manages the udev package and device rules'
description 'Manages the udev package and device rules'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
